apiVersion: apps/v1
kind: Deployment
metadata:
  name: e705-ui
spec:
  template:
    spec:
      containers:
        - name: e705-ui
          resources:
            limits:
              memory: 2Gi
              cpu: 500m  # Add CPU limit
            requests:
              cpu: 100m
              memory: 256Mi
      automountServiceAccountToken: false
