apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: e705-back
  namespace: doa-e705-dev
resources:
  - deployment.yaml
  - service.yaml
  - ingress-core.yaml
  - ingress-public.yaml
  - service-account.yaml
  - external-secret.yaml

# Common labels applied to all resources
labels:
  - pairs:
      app.kubernetes.io/name: e705-back
      app.kubernetes.io/instance: e705-back-service
      app.kubernetes.io/version: 1.0.1-854-e9551f4b
      app.kubernetes.io/component: e705-back
      app.kubernetes.io/part-of: e705-app

configMapGenerator:
  - name: e705-back-config
    files:
      - config/application.yaml
    literals:
      - SPRING_PROFILES_ACTIVE=dev
    options:
      disableNameSuffixHash: true

# Image transformations
images:
  - name: e705
    newName: finvmharborp01.finbel.intra/doa-e705/e705
    newTag: 1.0.1-854-e9551f4b
