apiVersion: v1
kind: Service
metadata:
  name: e705-back-service
  namespace: doa-e705-dev
  labels:
    app: e705-app
    version: 1.0.1-854-e9551f4b
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: management
  selector:
    app: e705-app
