apiVersion: v1
kind: Service
metadata:
  name: e705-ui-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: e705-ui
    app.kubernetes.io/instance: e705-ui-dev
